# Generated by Django 5.0.1 on 2024-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_description_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='repeat_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=1000),
        ),
    ]
