# Generated by Django 5.0.1 on 2024-02-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_classschedule_repeat_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='course',
        ),
    ]
